/**
 * Platform-wide money views for the admin dashboard: every wallet movement,
 * every invoice and every Razorpay payment link, joined to their sponsor.
 *
 * Everything is stored in paise and converted at this boundary, so no screen
 * ever does its own /100.
 */
import { supabase } from '@/lib/supabase';
import { formatDate, formatDateShort } from '@/lib/transforms';
import { logAudit } from '@/services/admin-writes';

export interface PaymentRow {
  id: string;
  sponsorId: string;
  sponsorName: string;
  amountRupees: number;
  kind: string;
  reference: string;
  date: string;
  /** ISO date (yyyy-mm-dd) for range filtering. */
  isoDate: string;
}

export async function fetchAllPayments(): Promise<PaymentRow[]> {
  if (!supabase) return [];
  const { data, error } = await supabase
    .from('wallet_transactions')
    .select('*, sponsor:sponsors(name)')
    .order('created_at', { ascending: false })
    .limit(500);
  if (error || !data) return [];
  return (data as any[]).map((t) => ({
    id: t.id,
    sponsorId: t.sponsor_id,
    sponsorName: t.sponsor?.name ?? 'Unknown',
    amountRupees: Number(t.amount_paise || 0) / 100,
    kind: t.kind,
    reference: t.reference ?? '',
    date: formatDateShort(t.created_at),
    isoDate: String(t.created_at).slice(0, 10),
  }));
}

export interface InvoiceRow {
  id: string;
  invoiceNumber: string;
  sponsorId: string;
  sponsorName: string;
  type: string;
  amountRupees: number;
  gstRupees: number;
  totalRupees: number;
  pdfUrl: string | null;
  sentViaEmail: boolean;
  date: string;
  isoDate: string;
}

export async function fetchAllInvoices(): Promise<InvoiceRow[]> {
  if (!supabase) return [];
  const { data, error } = await supabase
    .from('invoices')
    .select('*, sponsor:sponsors(name)')
    .order('created_at', { ascending: false })
    .limit(500);
  if (error || !data) return [];
  return (data as any[]).map((i) => ({
    id: i.id,
    invoiceNumber: i.invoice_number,
    sponsorId: i.sponsor_id,
    sponsorName: i.sponsor?.name ?? 'Unknown',
    type: i.type ?? 'wallet_topup',
    amountRupees: Number(i.amount_paise || 0) / 100,
    gstRupees: Number(i.gst_paise || 0) / 100,
    totalRupees: Number(i.total_paise || 0) / 100,
    pdfUrl: i.pdf_url ?? null,
    sentViaEmail: i.sent_via_email === true,
    date: formatDate(i.created_at),
    isoDate: String(i.created_at).slice(0, 10),
  }));
}

export interface PaymentLinkRow {
  id: string;
  sponsorId: string;
  sponsorName: string;
  amountRupees: number;
  shortUrl: string;
  status: string;
  purpose: string;
  date: string;
}

export async function fetchAllPaymentLinks(): Promise<PaymentLinkRow[]> {
  if (!supabase) return [];
  const { data, error } = await supabase
    .from('payment_links')
    .select('*, sponsor:sponsors(name)')
    .order('created_at', { ascending: false })
    .limit(300);
  if (error || !data) return [];
  return (data as any[]).map((l) => ({
    id: l.id,
    sponsorId: l.sponsor_id,
    sponsorName: l.sponsor?.name ?? 'Unknown',
    amountRupees: Number(l.amount_paise || 0) / 100,
    shortUrl: l.razorpay_short_url ?? '',
    status: l.status ?? 'created',
    purpose: l.purpose ?? 'wallet_topup',
    date: formatDate(l.created_at),
  }));
}

/**
 * Record a payment link the admin generated by hand in the Razorpay dashboard.
 * Used when the NestJS payments backend is not configured — it keeps the
 * ledger complete without this client ever touching a Razorpay secret.
 */
export async function recordManualPaymentLink(input: {
  sponsorId: string; amountRupees: number; shortUrl: string; purpose?: string;
}): Promise<void> {
  if (!supabase) throw new Error('Supabase not configured');
  const { error } = await supabase.from('payment_links').insert({
    sponsor_id: input.sponsorId,
    amount_paise: Math.round(input.amountRupees * 100),
    razorpay_short_url: input.shortUrl,
    purpose: input.purpose ?? 'wallet_topup',
    status: 'created',
  });
  if (error) throw error;
  await logAudit(`Recorded payment link ₹${input.amountRupees.toLocaleString('en-IN')}`);
}

export async function setPaymentLinkStatus(id: string, status: string): Promise<void> {
  if (!supabase) throw new Error('Supabase not configured');
  const patch: Record<string, unknown> = { status };
  if (status === 'paid') patch.paid_at = new Date().toISOString();
  const { error } = await supabase.from('payment_links').update(patch).eq('id', id);
  if (error) throw error;
  await logAudit(`Payment link ${id} → ${status}`);
}

/** GST is 18% on ad services; invoice numbers are sequential per financial year. */
export const GST_RATE = 0.18;

export async function createInvoice(input: {
  sponsorId: string; amountRupees: number; type?: string;
}): Promise<string> {
  if (!supabase) throw new Error('Supabase not configured');
  const gst = Math.round(input.amountRupees * GST_RATE);
  const total = input.amountRupees + gst;
  const invoiceNumber = `VAL-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`;
  const { error } = await supabase.from('invoices').insert({
    sponsor_id: input.sponsorId,
    invoice_number: invoiceNumber,
    type: input.type ?? 'wallet_topup',
    amount_paise: Math.round(input.amountRupees * 100),
    gst_paise: gst * 100,
    total_paise: total * 100,
  });
  if (error) throw error;
  await logAudit(`Created invoice ${invoiceNumber} (₹${total.toLocaleString('en-IN')})`);
  return invoiceNumber;
}

export async function markInvoiceEmailed(id: string, invoiceNumber: string): Promise<void> {
  if (!supabase) throw new Error('Supabase not configured');
  const { error } = await supabase.from('invoices').update({ sent_via_email: true }).eq('id', id);
  if (error) throw error;
  await logAudit(`Invoice ${invoiceNumber} marked emailed`);
}

export interface RevenueTotals {
  totalRupees: number;
  thisMonthRupees: number;
  thisWeekRupees: number;
  refundsRupees: number;
}

/**
 * Revenue is cash received, so only `topup` rows count. Negative rows are
 * campaign spend already funded by an earlier top-up (counting them would
 * double-count), and promotional bonus credits are not money the platform
 * received at all.
 */
export function revenueTotals(payments: PaymentRow[]): RevenueTotals {
  const now = new Date();
  const monthStart = new Date(now.getFullYear(), now.getMonth(), 1).toISOString().slice(0, 10);
  const weekStart = new Date(now.getTime() - 7 * 86400_000).toISOString().slice(0, 10);

  let total = 0, month = 0, week = 0, refunds = 0;
  for (const p of payments) {
    if (p.kind === 'refund') { refunds += Math.abs(p.amountRupees); continue; }
    if (p.kind !== 'topup' || p.amountRupees <= 0) continue;
    total += p.amountRupees;
    if (p.isoDate >= monthStart) month += p.amountRupees;
    if (p.isoDate >= weekStart) week += p.amountRupees;
  }
  return { totalRupees: total, thisMonthRupees: month, thisWeekRupees: week, refundsRupees: refunds };
}
